<a href="https://colab.research.google.com/github/shwanvas060/python/blob/master/back_propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#zurada exercise 4.14
import numpy as np

def bipolar(x):
    return (2/(1+np.exp(-x))-1)

z = np.array([1,3,-1])
v = np.array([[1,-2,3],[2,0,-1]])
w = np.array([[1,0,-2],[1,-2,3]])
d = np.array([0.95,0.05])
e = np.zeros(2,)
eta = 1
#---------------------------------------
print ("input z", z)
print("shape of z ", z.shape)
print("weights of v ", v)
print("shape of v ", v.shape)
print("weights of w", w)
print("shape of w ", w.shape)

print("d values", d)
#------------------------------------
#find y
net1 = np.dot(v,z)
print("net values of v and z:", net1)
y = []
for i in net1:
    out = bipolar(i)
    y = y+[out]
aug = [-1.0]
y = y+aug
y = np.array(y)
print("y values are: ")
print(y)
#-------------------------------------
#print("shape of w", w.shape)
#print ("shape of y", y.shape)
#-------------------------------------
#find o
net2 = np.dot(w,y)
print("net values of w and y:", net2)
ot = []
for j in net2:
    out = bipolar(j)
    ot = ot+[out]
ot = np.array(ot)
print("output values are ")
print(ot)
#-------------------------------------
#calculation of errors
error = (np.square(d-ot))+e
print("error - ", error)
#------------------------------------------
#calculation of deltaok
onem = np.ones(2,)
print(onem)
deltaok = 0.5*(d-ot)*(1-(ot**2))
print("deltaok value", deltaok)
#calculation of deltayj
deltaokw = deltaok.dot(w)
print(deltaokw)
deltayj = 0.5*(1-(y*y))*deltaokw
print("deltayj value ", deltayj)
#----------------------------------------------
#change in weights, w and v
yt = y.reshape(1,3)
deltaok = deltaok.reshape(2,1)
#print("shape of y ", y.shape)
print ("shape of yt", yt.shape)
print("shape of deltaok", deltaok.shape)
deltaoky = np.multiply(deltaok,yt)
print("value of deltaok with y", deltaoky)
w = w+(eta*deltaoky)
print("new weights w ", w)


input z [ 1  3 -1]
shape of z  (3,)
weights of v  [[ 1 -2  3]
 [ 2  0 -1]]
shape of v  (2, 3)
weights of w [[ 1  0 -2]
 [ 1 -2  3]]
shape of w  (2, 3)
d values [0.95 0.05]
net values of v and z: [-8  3]
y values are: 
[-0.9993293   0.90514825 -1.        ]
net values of w and y: [ 1.0006707  -5.80962581]
output values are 
[ 0.46238085 -0.99402083]
error -  [0.23777243 1.08997948]
[1. 1.]
deltaok value [0.19168405 0.00622372]
[ 0.19790777 -0.01244744 -0.36469694]
deltayj value  [ 0.00013269 -0.00112467 -0.        ]
shape of yt (1, 3)
shape of deltaok (2, 1)
value of deltaok with y [[-0.19155549  0.17350248 -0.19168405]
 [-0.00621955  0.00563339 -0.00622372]]
new weights w  [[ 0.80844451  0.17350248 -2.19168405]
 [ 0.99378045 -1.99436661  2.99377628]]


In [2]:
#change in weights, w and v
zt = z.reshape(1,3)
deltayj = deltayj.reshape(3,1)
#print("shape of y ", y.shape)
print ("shape of zt", zt.shape)
print("shape of deltayj", deltayj.shape)
deltayjz = np.multiply(deltayj,zt)
print("value of deltayj with z", deltayjz)
v = v+(eta*deltayjz)
print("new hidden weights v ", v)

NameError: ignored